language: python

python:
  - 2.7
  - 3.4
  - 3.7
  - 3.8

sudo: required

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libsmbclient-dev

install:
  - pip install .

script:
 - echo "can't test on Travis CI"
